name: Cleanup Signing
description: Clean up temporary signing resources

inputs:
  platform:
    description: 'Target platform'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cleanup macOS keychain
      if: inputs.platform == 'macOS'
      shell: bash
      run: |
        if [ -n "$R2MIDI_KEYCHAIN_PATH" ] && [ -f "$R2MIDI_KEYCHAIN_PATH" ]; then
          echo "🧹 Cleaning up temporary keychain..."
          security delete-keychain "$R2MIDI_KEYCHAIN_PATH" || true
        fi
        
        # Clean up notarization profile
        xcrun notarytool credentials list | grep "r2midi-notary" && \
          xcrun notarytool credentials delete "r2midi-notary" || true
        
        echo "✅ Cleanup completed"

    - name: Cleanup Windows certificates
      if: inputs.platform == 'windows'
      shell: pwsh
      run: |
        Write-Host "🧹 Cleaning up Windows certificates..."
        # Add Windows certificate cleanup if needed
