name: Build Applications (Updated)
description: Build applications using direct macOS build or Briefcase

inputs:
  platform:
    description: 'Target platform'
    required: true
  sign:
    description: 'Whether to sign builds'
    required: false
    default: 'false'

outputs:
  server-app-path:
    description: 'Path to the server .app bundle (macOS only)'
    value: ${{ steps.macos-build.outputs.server-app-path }}
  client-app-path:
    description: 'Path to the client .app bundle (macOS only)'
    value: ${{ steps.macos-build.outputs.client-app-path }}

runs:
  using: "composite"
  steps:
    - name: Build macOS applications (Direct)
      id: macos-build
      if: inputs.platform == 'macOS'
      uses: ./.github/actions/build-macos-direct
      with:
        version: ${{ env.APP_VERSION }}
        sign: ${{ inputs.sign }}

    - name: Create applications (Other platforms)
      if: inputs.platform != 'macOS'
      shell: bash
      run: |
        echo "🔨 Creating applications for ${{ inputs.platform }}..."
        
        # Determine app type based on platform
        if [ "${{ inputs.platform }}" = "linux" ]; then
          APP_TYPE="system"
        else
          APP_TYPE="app"
        fi
        
        # Create server
        echo "Creating R2MIDI Server..."
        briefcase create ${{ inputs.platform }} $APP_TYPE -a server
        
        # Create client
        echo "Creating R2MIDI Client..."
        briefcase create ${{ inputs.platform }} $APP_TYPE -a r2midi-client

    - name: Build applications (Other platforms)
      if: inputs.platform != 'macOS'
      shell: bash
      run: |
        echo "⚙️ Building applications for ${{ inputs.platform }}..."
        
        # Determine app type based on platform
        if [ "${{ inputs.platform }}" = "linux" ]; then
          APP_TYPE="system"
        else
          APP_TYPE="app"
        fi
        
        # Build server
        echo "Building R2MIDI Server..."
        briefcase build ${{ inputs.platform }} $APP_TYPE -a server
        
        # Build client
        echo "Building R2MIDI Client..."
        briefcase build ${{ inputs.platform }} $APP_TYPE -a r2midi-client

    - name: List build output
      shell: bash
      run: |
        echo "📁 Build output:"
        if [ "${{ inputs.platform }}" = "macOS" ]; then
          echo "macOS apps built with direct method:"
          echo "Server: ${{ steps.macos-build.outputs.server-app-path }}"
          echo "Client: ${{ steps.macos-build.outputs.client-app-path }}"
        else
          if [ -d "build" ]; then
            find build -type f \( -name "*.app" -o -name "*.exe" -o -name "*.deb" \) | head -20
          fi
        fi