name: Build Linux

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Application version'
      build-type:
        required: false
        type: string
        default: 'production'
        description: 'Build type (dev, staging, production)'
    outputs:
      artifact-name:
        description: "Name of the uploaded artifact"
        value: ${{ jobs.build-linux.outputs.artifact-name }}
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type'
        required: false
        type: choice
        options:
          - dev
          - staging
          - production
        default: 'dev'

jobs:
  build-linux:
    name: Build Linux Apps
    runs-on: ubuntu-latest
    timeout-minutes: 45
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            r2midi_client/requirements.txt

      - name: Extract version information
        id: version
        shell: bash
        run: |
          ./.github/scripts/extract-version.sh "${{ inputs.version }}"

      - name: Validate build environment
        shell: bash
        run: |
          ./.github/scripts/validate-build-environment.sh linux

      - name: Install system dependencies
        shell: bash
        run: |
          ./.github/scripts/install-system-dependencies.sh linux

      - name: Install Python dependencies
        shell: bash
        run: |
          ./.github/scripts/install-python-dependencies.sh production

      - name: Build applications
        shell: bash
        run: |
          ./.github/scripts/build-briefcase-apps.sh linux unsigned

      - name: Package applications
        shell: bash
        run: |
          ./.github/scripts/package-linux-apps.sh "${{ steps.version.outputs.version }}" "${{ inputs.build-type }}"

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ inputs.build-type }}-${{ github.run_number }}
          path: artifacts/
          retention-days: ${{ inputs.build-type == 'production' && 90 || 30 }}
          compression-level: 6

      - name: Build summary
        shell: bash
        run: |
          ./.github/scripts/generate-build-summary.sh linux "${{ inputs.build-type }}" "${{ steps.version.outputs.version }}" unsigned